etcdcluster:
  hosts:
    - 127.0.0.1:2379
etcdwatcher:
  keys:
    -
      key: foo
      privilege: high
    -
      key: foo2
      privilege: low
    -
      key: foo3
      privilege: mid

redis:
  network: tcp
  addr: 127.0.0.1:6379
  db: 0
  maxretries: 5
  poolsize: 10000
