etcdcluster:
  hosts:
    - 0.0.0.0:2379
etcdwatcher:
  keys:
    -
      key: foo
      privilege: high
    -
      key: foo2
      privilege: low
    -
      key: foo3
      privilege: mid

redis:
  network: tcp
  addr: 0.0.0.0:6379
  db: 0
  maxretries: 5
  poolsize: 10000
  password: Hello123

logger:
  filepath: ./watch.log